### ISSUE TITLE
Installation errors using setup.py

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/pymainstay#3]
After installing using setup.py and running msc, the following additional pythonn packages has to be installed:
```appdirs```
```pygit```

After installing the above I get the following error: 
```
Lawrences-MacBook-Pro:pymainstay lawrence$ msc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/msc", line 11, in <module>
    load_entry_point('pymainstay==0.1.0', 'console_scripts', 'msc')()
  File "/Users/lawrence/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/lawrence/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/Users/lawrence/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/Users/lawrence/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymainstay-0.1.0-py3.6.egg/mst/mainstay.py", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymainstay-0.1.0-py3.6.egg/mst/args.py", line 7, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymainstay-0.1.0-py3.6.egg/mst/cmds.py", line 15, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/__init__.py", line 6, in <module>
    from repository import Repository, InvalidRepositoryError
ModuleNotFoundError: No module named 'repository'
```

**Comment by lawlawlaw** [comment]
> After installing using setup.py and running msc, the following additional pythonn packages has to be installed:
> `appdirs`
> `pygit`
> 
> After installing the above I get the following error:
> 
> ```
> Lawrences-MacBook-Pro:pymainstay lawrence$ msc
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/msc", line 11, in <module>
>     load_entry_point('pymainstay==0.1.0', 'console_scripts', 'msc')()
>   File "/Users/lawrence/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/Users/lawrence/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
>     return ep.load()
>   File "/Users/lawrence/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 2321, in load
>     return self.resolve()
>   File "/Users/lawrence/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 2327, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymainstay-0.1.0-py3.6.egg/mst/mainstay.py", line 4, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymainstay-0.1.0-py3.6.egg/mst/args.py", line 7, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymainstay-0.1.0-py3.6.egg/mst/cmds.py", line 15, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/__init__.py", line 6, in <module>
>     from repository import Repository, InvalidRepositoryError
> ModuleNotFoundError: No module named 'repository'
> ```

Resolved this by installing the package ```gitpython```
