### ISSUE TITLE
Handle fetch from slot with 0 commitments

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/pymainstay#5]
Crashed when fetching from a slot with 0 commitments:

```Lawrences-MacBook-Pro:pymainstay lawrence$ msc fetch -s 3 -i 0
No configuration file found
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/msc", line 11, in <module>
    load_entry_point('pymainstay==0.1.0', 'console_scripts', 'msc')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymainstay-0.1.0-py3.6.egg/mst/mainstay.py", line 23, in main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymainstay-0.1.0-py3.6.egg/mst/cmds.py", line 438, in fetch_command
TypeError: object of type 'NoneType' has no len()```

**Comment by tomt1664** [comment]
Fixed with a493769fb5b10cf881f945cb63b2d79fb9ab41e3
